package install

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"phatmon/internal/config"
)

type envFile struct {
	path string
	data []byte
	mode os.FileMode
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}

func prepareEnvironment(opts Options, homes []config.Home) ([]envFile, error) {
	if opts.NoHomeEnv {
		return nil, nil
	}
	variable := opts.EndpointEnv
	if variable == "" {
		variable = "CODEX_REMOTE"
	}
	if !regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`).MatchString(variable) || variable == "CODEX_HOME" {
		return nil, fmt.Errorf("endpoint-env must be a shell variable name distinct from CODEX_HOME")
	}
	var files []envFile
	for _, home := range homes {
		data := "# Generated by phatmon install. Source from direnv or your shell.\n" +
			"export CODEX_HOME=" + shellQuote(home.Path) + "\n" +
			"export " + variable + "=" + shellQuote(home.Endpoint) + "\n"
		files = append(files, envFile{filepath.Join(home.Path, "phatmon.env"), []byte(data), 0600})
	}
	return files, nil
}
