package install

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"phatmon/internal/config"
)

func TestEnvironmentMatchesServicesAndDoesNotChangeShell(t *testing.T) {
	opts := fixture(t)
	root := os.Getenv("HOME")
	extra := filepath.Join(root, ".codex-homes", "lab with 'quotes' $literal")
	if err := os.MkdirAll(extra, 0700); err != nil {
		t.Fatal(err)
	}
	original := []byte("# user's existing file\n")
	protected := []string{filepath.Join(root, ".zshrc"), filepath.Join(root, ".bashrc"), filepath.Join(root, ".envrc"), filepath.Join(opts.BinDir, "codex")}
	for _, path := range protected {
		if err := writeFile(path, original, 0644); err != nil {
			t.Fatal(err)
		}
	}
	for _, addr := range []string{opts.WorkAddr, "ws://127.0.0.1:4510"} {
		opts.WorkAddr = addr
		if err := Run(opts, &bytes.Buffer{}); err != nil {
			t.Fatal(err)
		}
		conf, err := config.Load(opts.ConfigPath)
		if err != nil {
			t.Fatal(err)
		}
		for _, h := range conf.Homes {
			path := filepath.Join(h.Path, "phatmon.env")
			cmd := exec.Command("/bin/sh", "-c", ". \"$1\"; printf '%s\\000' \"$CODEX_HOME\" \"$CODEX_REMOTE\"", "sh", path)
			output, err := cmd.CombinedOutput()
			if err != nil {
				t.Fatalf("source env: %s, %v", output, err)
			}
			got := strings.Split(strings.TrimSuffix(string(output), "\x00"), "\x00")
			if !reflect.DeepEqual(got, []string{h.Path, h.Endpoint}) {
				t.Fatalf("wrong home environment: %#v", got)
			}
			unit, err := os.ReadFile(filepath.Join(opts.UnitDir, serviceName(h, opts)))
			if err != nil || !strings.Contains(string(unit), h.Endpoint) {
				t.Fatalf("environment/server mismatch: %s, %v", unit, err)
			}
			if _, err := os.Stat(filepath.Join(h.Path, "bin", "codex")); !os.IsNotExist(err) {
				t.Fatal("home launcher installed")
			}
		}
	}
	for _, path := range protected {
		got, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(got, original) {
			t.Fatalf("user file changed: %s", path)
		}
	}
}

func TestEnvironmentVariableAndStagingOptions(t *testing.T) {
	opts := fixture(t)
	opts.EndpointEnv = "CODEX_APP_SERVER_URL"
	if err := Run(opts, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(os.Getenv("HOME"), ".codex", "phatmon.env")
	data, _ := os.ReadFile(path)
	if !strings.Contains(string(data), "export CODEX_APP_SERVER_URL=") || strings.Contains(string(data), "CODEX_REMOTE") {
		t.Fatalf("wrong variable: %s", data)
	}
	opts.NoHomeEnv = true
	if err := os.Remove(path); err != nil {
		t.Fatal(err)
	}
	if err := Run(opts, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatal("staged install wrote home env")
	}
	for _, variable := range []string{"BAD;command", "CODEX_HOME", "1INVALID"} {
		opts.NoHomeEnv = false
		opts.EndpointEnv = variable
		if err := Run(opts, &bytes.Buffer{}); err == nil {
			t.Fatalf("invalid variable accepted: %s", variable)
		}
	}
}

func TestUpgradeRemovesOnlyManagedLaunchersAndHooks(t *testing.T) {
	opts := fixture(t)
	root := os.Getenv("HOME")
	t.Setenv("ZDOTDIR", "")
	originalCodex := opts.Codex
	conf, err := config.Defaults()
	if err != nil {
		t.Fatal(err)
	}
	conf.Settings.CodexBinary = originalCodex
	if err := config.Save(opts.ConfigPath, conf); err != nil {
		t.Fatal(err)
	}
	launcher := []byte("#!/bin/sh\n# phatmon-managed-codex-launcher\nexit 1\n")
	paths := []string{filepath.Join(opts.BinDir, "codex"), filepath.Join(root, ".codex", "bin", "codex")}
	for _, path := range paths {
		if err := writeFile(path, launcher, 0755); err != nil {
			t.Fatal(err)
		}
	}
	hook := filepath.Join(filepath.Dir(opts.ConfigPath), "shell.sh")
	if err := writeFile(hook, []byte("# Generated by Phatmon.\nexport PATH='old':\"$PATH\"\n"), 0644); err != nil {
		t.Fatal(err)
	}
	rc := filepath.Join(root, ".zshrc")
	block := "# >>> phatmon Codex client >>>\n. " + shellQuote(hook) + "\n# <<< phatmon Codex client <<<"
	if err := writeFile(rc, []byte("# before\n"+block+"\n# after\n"), 0600); err != nil {
		t.Fatal(err)
	}
	opts.Codex = paths[0]
	if err := Run(opts, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	for _, path := range paths {
		if _, err := os.Stat(path); !os.IsNotExist(err) {
			t.Fatalf("legacy launcher retained: %s", path)
		}
	}
	data, _ := os.ReadFile(rc)
	if string(data) != "# before\n\n# after\n" {
		t.Fatalf("shell cleanup changed unrelated lines: %s", data)
	}
	data, _ = os.ReadFile(hook)
	if strings.Contains(string(data), "export PATH") {
		t.Fatal("legacy PATH hook still active")
	}
	saved, err := config.Load(opts.ConfigPath)
	if err != nil || saved.Settings.CodexBinary != originalCodex {
		t.Fatalf("lost original Codex: %v", err)
	}
}
