package install

import (
	"io"
	"os"
	"path/filepath"
	"strings"

	"phatmon/internal/config"
)

// Recognize only the launchers emitted by the previous installer.
func legacyLauncher(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	data := make([]byte, 256)
	n, _ := io.ReadFull(f, data)
	return strings.Contains(string(data[:n]), "# phatmon-managed-codex-launcher")
}

func removeLegacyClients(opts Options, homes []config.Home) error {
	if opts.NoHomeEnv {
		return nil
	}
	paths := []string{filepath.Join(opts.BinDir, "codex")}
	for _, home := range homes {
		paths = append(paths, filepath.Join(home.Path, "bin", "codex"))
	}
	for _, path := range paths {
		if legacyLauncher(path) {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}
	hook := filepath.Join(filepath.Dir(opts.ConfigPath), "shell.sh")
	block := "# >>> phatmon Codex client >>>\n. " + shellQuote(hook) + "\n# <<< phatmon Codex client <<<"
	user, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	rcs := []string{filepath.Join(user, ".bashrc"), filepath.Join(user, ".zshrc")}
	if dir := os.Getenv("ZDOTDIR"); dir != "" {
		rcs = append(rcs, filepath.Join(dir, ".zshrc"))
	}
	for _, path := range rcs {
		data, err := os.ReadFile(path)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}
		if !strings.Contains(string(data), block) {
			continue
		}
		path, err = config.Expand(path)
		if err != nil {
			return err
		}
		info, err := os.Stat(path)
		if err != nil {
			return err
		}
		if err := writeFile(path, []byte(strings.ReplaceAll(string(data), block, "")), info.Mode().Perm()); err != nil {
			return err
		}
	}
	// An earlier custom --shell-rc may still source this path. Keep it harmless.
	data, err := os.ReadFile(hook)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if strings.HasPrefix(string(data), "# Generated by Phatmon.\nexport PATH=") {
		return writeFile(hook, []byte("# Phatmon client routing has been removed. Use per-home phatmon.env files.\n"), 0644)
	}
	return nil
}
